# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macOS-latest', 'windows-latest']
        go: ['1.20', '1.21', '1.22', '1.23', '1.24']
        arch: ['']
        include:
          - os: 'ubuntu-latest'
            go: '1.24'
            arch: '386'
          - os: 'ubuntu-latest'
            go: '1.20'
            arch: '386'
          - os: 'windows-latest'
            go: '1.24'
            arch: '386'
          - os: 'windows-latest'
            go: '1.20'
            arch: '386'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -count=1 -v -failfast -cover ./...
      env:
        GOARCH: ${{ matrix.arch }}

    - name: Test with race detector
      if: ${{ matrix.arch == '' }}
      run: go test -count=10 -v -race -failfast -cover ./...
      env:
        GORACE: 'halt_on_error=1'
